kj_fix_order_slip_total_settings:
  path: /kjfixordersliptotal/settings
  methods: [GET]
  defaults:
    _controller: 'Kaudaj\Module\FixOrderSlipTotal\Controller\Admin\SettingsController::indexAction'
    _legacy_controller: KJFixOrderSlipTotalSettings

kj_fix_order_slip_total_settings_general_save:
  path: /kjfixordersliptotal/settings/general
  methods: [POST, PATCH]
  defaults:
    _controller: 'Kaudaj\Module\FixOrderSlipTotal\Controller\Admin\SettingsController::processGeneralFormAction'
    _legacy_controller: KJFixOrderSlipTotalSettings
    _legacy_link: KJFixOrderSlipTotalSettings:update
