services:
  _defaults:
    public: true

  kaudaj.module.fix_order_slip_total.adapter.order.query_handler.get_order_for_viewing_handler:
    class: Kaudaj\Module\FixOrderSlipTotal\Adapter\Order\QueryHandler\GetOrderForViewingHandler
    decorates: prestashop.adapter.order.query_handler.get_order_for_viewing_handler
    arguments:
      - "@kaudaj.module.fix_order_slip_total.adapter.order.query_handler.get_order_for_viewing_handler.inner"
      - "@translator"
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'
      - "@prestashop.core.localization.locale.context_locale"
      - "@prestashop.adapter.legacy.configuration"
